language: java
jdk: oraclejdk8

# Improve Build Speed https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
  - $HOME/.m2

# JaCoCo https://github.com/codecov/example-java
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Notifications https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    recipients:
      - rmuskovets@gmail.com
    on_success: always # default: change
    on_failure: always # default: always